# Generated by Django 4.2.19 on 2025-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Match Updates"),
                    (2, "Team News"),
                    (3, "Player Stats"),
                    (4, "Fan Discussions"),
                    (5, "Memes"),
                    (6, "Points Table"),
                    (7, "Teams"),
                ]
            ),
        ),
    ]
